const AUTH_CACHE_KEY = ["@Auth:currentUser"];
const HISTORY_TREINAMENTOS_LIST_CACHE_KEY = ["@Treinamentos:history"]
const TREINOS_LIST_CACHE_KEY = ["@Treinos:list"]
const TREINO_DETAILS_CACHE_KEY = "@Treinos:details"
const TREINAMENTO_SERIES_CACHE_KEY = "@Treinamentos:series"
const CURRENT_TREINAMENTO_CACHE_KEY = ["@Treinamentos:current"]

export const STORAGE_KEYS = {
    AUTH_CACHE_KEY,
    HISTORY_TREINAMENTOS_LIST_CACHE_KEY,
    TREINOS_LIST_CACHE_KEY,
    TREINO_DETAILS_CACHE_KEY,
    TREINAMENTO_SERIES_CACHE_KEY,
    CURRENT_TREINAMENTO_CACHE_KEY
}
