spring.application.name=backend
server.port=${SERVER_PORT:8080}
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:minha-secret-secreta-poha}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Configuração de Conexão com o Banco
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gym}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
# "update": cria/atualiza tabelas automaticamente baseado nas Entidades
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# Mostra as queries SQL no console (útil para debug)
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Timezone configs
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
